//
// Generated file, do not edit! Created by nedtool 5.5 from core4inet/base/avb/AVBDefs.msg.
//

#ifndef __CORE4INET_AVBDEFS_M_H
#define __CORE4INET_AVBDEFS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace CoRE4INET {

} // namespace CoRE4INET

#endif // ifndef __CORE4INET_AVBDEFS_M_H

