//
// Generated file, do not edit! Created by nedtool 5.5 from core4inet/base/IPoRE/IPoREDefs.msg.
//

#ifndef __CORE4INET_IPOREDEFS_M_H
#define __CORE4INET_IPOREDEFS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace CoRE4INET {

/**
 * Enum generated from <tt>core4inet/base/IPoRE/IPoREDefs.msg:22</tt> by nedtool.
 * <pre>
 * //Destination Types for IP traffic filter
 * //
 * // \@author Kai v. Deylen
 * enum DestinationType
 * {
 *     DestinationType_AVB = 0; //Destination tyee for AVB traffic
 *     DestinationType_TT = 1; //Destination type for time-triggeres traffic
 *     DestinationType_RC = 2; //Destination type for rate-constrained traffic
 *     DestinationType_8021Q = 3; //Destination type for IEEE 802.1Q traffic
 *     DestinationType_invalid = 0xFF; //Destination type for rate-constrained traffic
 * }
 * </pre>
 */
enum DestinationType {
    DestinationType_AVB = 0,
    DestinationType_TT = 1,
    DestinationType_RC = 2,
    DestinationType_8021Q = 3,
    DestinationType_invalid = 0xFF
};

} // namespace CoRE4INET

#endif // ifndef __CORE4INET_IPOREDEFS_M_H

