//
// Generated file, do not edit! Created by nedtool 5.5 from core4inet/linklayer/ethernet/AS6802/RCFrame.msg.
//

#ifndef __CORE4INET_RCFRAME_M_H
#define __CORE4INET_RCFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    //CoRE4INET
	#include "core4inet/linklayer/ethernet/AS6802/CTFrame.h"
// }}


namespace CoRE4INET {

/**
 * Class generated from <tt>core4inet/linklayer/ethernet/AS6802/RCFrame.msg:35</tt> by nedtool.
 * <pre>
 * //
 * // Represents a RC frame
 * //
 * // \@see ~CTFrame
 * //
 * // \@author Till Steinbach
 * //
 * packet RCFrame extends CTFrame
 * {
 *     string displayString = "b=15,15,rect,black,orange,5";
 * }
 * </pre>
 */
class RCFrame : public ::CoRE4INET::CTFrame
{
  protected:
    ::omnetpp::opp_string displayString;

  private:
    void copy(const RCFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RCFrame&);

  public:
    RCFrame(const char *name=nullptr, short kind=0);
    RCFrame(const RCFrame& other);
    virtual ~RCFrame();
    RCFrame& operator=(const RCFrame& other);
    virtual RCFrame *dup() const override {return new RCFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RCFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RCFrame& obj) {obj.parsimUnpack(b);}

} // namespace CoRE4INET

#endif // ifndef __CORE4INET_RCFRAME_M_H

