//
// Generated file, do not edit! Created by nedtool 5.5 from core4inet/scheduler/SchedulerMessageEvents.msg.
//

#ifndef __CORE4INET_SCHEDULERMESSAGEEVENTS_M_H
#define __CORE4INET_SCHEDULERMESSAGEEVENTS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    //CoRE4INET
    #include "core4inet/scheduler/SchedulerEvent.h"
// }}


namespace CoRE4INET {

/**
 * Class generated from <tt>core4inet/scheduler/SchedulerMessageEvents.msg:33</tt> by nedtool.
 * <pre>
 * //
 * // Message used for events of TTEScheduler that are triggered at a specified time in cycle (action_time).
 * // Should be created with message kind SchedulerMessageKind = ACTION_TIME_EVENT
 * //
 * // \@see ~SchedulerEvent, ~SchedulerMessageKind
 * //
 * // \@author Till Steinbach
 * //
 * message SchedulerActionTimeEvent extends SchedulerEvent
 * {
 *     // Action time in cycle for the event in number of ticks
 *     uint32_t action_time;
 *     //force execution in next cycle at the earliest
 *     bool next_cycle;
 * }
 * </pre>
 */
class SchedulerActionTimeEvent : public ::CoRE4INET::SchedulerEvent
{
  protected:
    uint32_t action_time;
    bool next_cycle;

  private:
    void copy(const SchedulerActionTimeEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SchedulerActionTimeEvent&);

  public:
    SchedulerActionTimeEvent(const char *name=nullptr, short kind=0);
    SchedulerActionTimeEvent(const SchedulerActionTimeEvent& other);
    virtual ~SchedulerActionTimeEvent();
    SchedulerActionTimeEvent& operator=(const SchedulerActionTimeEvent& other);
    virtual SchedulerActionTimeEvent *dup() const override {return new SchedulerActionTimeEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint32_t getAction_time() const;
    virtual void setAction_time(uint32_t action_time);
    virtual bool getNext_cycle() const;
    virtual void setNext_cycle(bool next_cycle);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SchedulerActionTimeEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SchedulerActionTimeEvent& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>core4inet/scheduler/SchedulerMessageEvents.msg:48</tt> by nedtool.
 * <pre>
 * //
 * // Message used for events of TTEScheduler that are triggered after a specified time (timer).
 * // Should be created with message kind SchedulerMessageKind = TIMER_EVENT
 * //
 * // \@see ~SchedulerEvent, ~SchedulerMessageKind
 * //
 * // \@author Till Steinbach
 * //
 * message SchedulerTimerEvent extends SchedulerEvent
 * {
 *     // Time after that the event is triggered in number of ticks
 *     uint64_t timer;
 * }
 * </pre>
 */
class SchedulerTimerEvent : public ::CoRE4INET::SchedulerEvent
{
  protected:
    uint64_t timer;

  private:
    void copy(const SchedulerTimerEvent& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SchedulerTimerEvent&);

  public:
    SchedulerTimerEvent(const char *name=nullptr, short kind=0);
    SchedulerTimerEvent(const SchedulerTimerEvent& other);
    virtual ~SchedulerTimerEvent();
    SchedulerTimerEvent& operator=(const SchedulerTimerEvent& other);
    virtual SchedulerTimerEvent *dup() const override {return new SchedulerTimerEvent(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint64_t getTimer() const;
    virtual void setTimer(uint64_t timer);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SchedulerTimerEvent& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SchedulerTimerEvent& obj) {obj.parsimUnpack(b);}

} // namespace CoRE4INET

#endif // ifndef __CORE4INET_SCHEDULERMESSAGEEVENTS_M_H

