//
// Generated file, do not edit! Created by nedtool 5.5 from openflow/messages/HF_ChangeNotification.msg.
//

#ifndef __OPENFLOW_HF_CHANGENOTIFICATION_M_H
#define __OPENFLOW_HF_CHANGENOTIFICATION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "inet/linklayer/ethernet/EtherFrame_m.h"
    #include "openflow/hyperflow/HyperFlowStructs.h"
    
// }}


namespace openflow {

/**
 * Class generated from <tt>openflow/messages/HF_ChangeNotification.msg:15</tt> by nedtool.
 * <pre>
 * // When packets are received by the data plane and sent to the connected controller,
 * // the OFP_PACKET_IN messages are used. If the complete packet needs to be sent to the controller, because it can not be
 * // stored in the bufer, it is encapsulated in the packet-in message.
 * packet HF_ChangeNotification
 * {
 *     DataChannelEntry entry;
 * }
 * </pre>
 */
class HF_ChangeNotification : public ::omnetpp::cPacket
{
  protected:
    DataChannelEntry entry;

  private:
    void copy(const HF_ChangeNotification& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HF_ChangeNotification&);

  public:
    HF_ChangeNotification(const char *name=nullptr, short kind=0);
    HF_ChangeNotification(const HF_ChangeNotification& other);
    virtual ~HF_ChangeNotification();
    HF_ChangeNotification& operator=(const HF_ChangeNotification& other);
    virtual HF_ChangeNotification *dup() const override {return new HF_ChangeNotification(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual DataChannelEntry& getEntry();
    virtual const DataChannelEntry& getEntry() const {return const_cast<HF_ChangeNotification*>(this)->getEntry();}
    virtual void setEntry(const DataChannelEntry& entry);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HF_ChangeNotification& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HF_ChangeNotification& obj) {obj.parsimUnpack(b);}

} // namespace openflow

#endif // ifndef __OPENFLOW_HF_CHANGENOTIFICATION_M_H

