//
// Generated file, do not edit! Created by nedtool 5.5 from openflow/messages/HF_SyncRequest.msg.
//

#ifndef __OPENFLOW_HF_SYNCREQUEST_M_H
#define __OPENFLOW_HF_SYNCREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "inet/linklayer/ethernet/EtherFrame_m.h"
    
    
// }}


namespace openflow {

/**
 * Class generated from <tt>openflow/messages/HF_SyncRequest.msg:14</tt> by nedtool.
 * <pre>
 * // When packets are received by the data plane and sent to the connected controller,
 * // the OFP_PACKET_IN messages are used. If the complete packet needs to be sent to the controller, because it can not be
 * // stored in the bufer, it is encapsulated in the packet-in message.
 * packet HF_SyncRequest
 * {
 *     int lastSyncCounter;
 * }
 * </pre>
 */
class HF_SyncRequest : public ::omnetpp::cPacket
{
  protected:
    int lastSyncCounter;

  private:
    void copy(const HF_SyncRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const HF_SyncRequest&);

  public:
    HF_SyncRequest(const char *name=nullptr, short kind=0);
    HF_SyncRequest(const HF_SyncRequest& other);
    virtual ~HF_SyncRequest();
    HF_SyncRequest& operator=(const HF_SyncRequest& other);
    virtual HF_SyncRequest *dup() const override {return new HF_SyncRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getLastSyncCounter() const;
    virtual void setLastSyncCounter(int lastSyncCounter);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HF_SyncRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HF_SyncRequest& obj) {obj.parsimUnpack(b);}

} // namespace openflow

#endif // ifndef __OPENFLOW_HF_SYNCREQUEST_M_H

