//
// Generated file, do not edit! Created by nedtool 5.5 from openflow/messages/LLDP.msg.
//

#ifndef __OPENFLOW_LLDP_M_H
#define __OPENFLOW_LLDP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "inet/linklayer/ethernet/EtherFrame_m.h"
    
    
// }}


namespace openflow {

/**
 * Class generated from <tt>openflow/messages/LLDP.msg:14</tt> by nedtool.
 * <pre>
 * // When packets are received by the data plane and sent to the connected controller,
 * // the OFP_PACKET_IN messages are used. If the complete packet needs to be sent to the controller, because it can not be
 * // stored in the bufer, it is encapsulated in the packet-in message.
 * packet LLDP
 * {
 *     int portID;
 *     string chassisID;
 *     double ttl;
 * }
 * </pre>
 */
class LLDP : public ::omnetpp::cPacket
{
  protected:
    int portID;
    ::omnetpp::opp_string chassisID;
    double ttl;

  private:
    void copy(const LLDP& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LLDP&);

  public:
    LLDP(const char *name=nullptr, short kind=0);
    LLDP(const LLDP& other);
    virtual ~LLDP();
    LLDP& operator=(const LLDP& other);
    virtual LLDP *dup() const override {return new LLDP(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getPortID() const;
    virtual void setPortID(int portID);
    virtual const char * getChassisID() const;
    virtual void setChassisID(const char * chassisID);
    virtual double getTtl() const;
    virtual void setTtl(double ttl);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LLDP& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LLDP& obj) {obj.parsimUnpack(b);}

} // namespace openflow

#endif // ifndef __OPENFLOW_LLDP_M_H

