//
// Generated file, do not edit! Created by nedtool 5.5 from openflow/messages/OFP_Stats_Reply.msg.
//

#ifndef __OPENFLOW_OFP_STATS_REPLY_M_H
#define __OPENFLOW_OFP_STATS_REPLY_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "openflow/openflow/protocol/OpenFlow.h"
    #include "openflow/messages/Open_Flow_Message_m.h"
    
// }}


namespace openflow {

/**
 * Class generated from <tt>openflow/messages/OFP_Stats_Reply.msg:27</tt> by nedtool.
 * <pre>
 * packet OFP_Stats_Reply extends Open_Flow_Message
 * {
 * }
 * </pre>
 */
class OFP_Stats_Reply : public ::openflow::Open_Flow_Message
{
  protected:
    std::vector<int> tx_packets;
  private:
    void copy(const OFP_Stats_Reply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OFP_Stats_Reply&);

  public:
    OFP_Stats_Reply(const char *name=nullptr, short kind=0);
    OFP_Stats_Reply(const OFP_Stats_Reply& other);
    virtual ~OFP_Stats_Reply();
    OFP_Stats_Reply& operator=(const OFP_Stats_Reply& other);
    virtual OFP_Stats_Reply *dup() const override {return new OFP_Stats_Reply(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    std::vector<int> getTxPackets() const;
    void  setTxPackets(std::vector<int> tmp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OFP_Stats_Reply& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OFP_Stats_Reply& obj) {obj.parsimUnpack(b);}

} // namespace openflow

#endif // ifndef __OPENFLOW_OFP_STATS_REPLY_M_H

