//
// Generated file, do not edit! Created by nedtool 5.5 from openflow/messages/OFP_Hello.msg.
//

#ifndef __OPENFLOW_OFP_HELLO_M_H
#define __OPENFLOW_OFP_HELLO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "openflow/openflow/protocol/OpenFlow.h"
    #include "openflow/messages/Open_Flow_Message_m.h"    
    
// }}


namespace openflow {

/**
 * Class generated from <tt>openflow/messages/OFP_Hello.msg:15</tt> by nedtool.
 * <pre>
 * packet OFP_Hello extends Open_Flow_Message
 * {
 * }
 * </pre>
 */
class OFP_Hello : public ::openflow::Open_Flow_Message
{
  protected:

  private:
    void copy(const OFP_Hello& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OFP_Hello&);

  public:
    OFP_Hello(const char *name=nullptr, short kind=0);
    OFP_Hello(const OFP_Hello& other);
    virtual ~OFP_Hello();
    OFP_Hello& operator=(const OFP_Hello& other);
    virtual OFP_Hello *dup() const override {return new OFP_Hello(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OFP_Hello& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OFP_Hello& obj) {obj.parsimUnpack(b);}

} // namespace openflow

#endif // ifndef __OPENFLOW_OFP_HELLO_M_H

