//
// Generated file, do not edit! Created by nedtool 5.5 from openflow/messages/Open_Flow_Message.msg.
//

#ifndef __OPENFLOW_OPEN_FLOW_MESSAGE_M_H
#define __OPENFLOW_OPEN_FLOW_MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "openflow/openflow/protocol/OpenFlow.h"
// }}


namespace openflow {

/**
 * Class generated from <tt>openflow/messages/Open_Flow_Message.msg:13</tt> by nedtool.
 * <pre>
 * // base class for all OpenFlow protocol messages; only contains the OpenFlow header
 * packet Open_Flow_Message
 * {
 *     ofp_header header;
 * 
 * }
 * </pre>
 */
class Open_Flow_Message : public ::omnetpp::cPacket
{
  protected:
    ofp_header header;

  private:
    void copy(const Open_Flow_Message& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Open_Flow_Message&);

  public:
    Open_Flow_Message(const char *name=nullptr, short kind=0);
    Open_Flow_Message(const Open_Flow_Message& other);
    virtual ~Open_Flow_Message();
    Open_Flow_Message& operator=(const Open_Flow_Message& other);
    virtual Open_Flow_Message *dup() const override {return new Open_Flow_Message(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ofp_header& getHeader();
    virtual const ofp_header& getHeader() const {return const_cast<Open_Flow_Message*>(this)->getHeader();}
    virtual void setHeader(const ofp_header& header);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Open_Flow_Message& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Open_Flow_Message& obj) {obj.parsimUnpack(b);}

} // namespace openflow

#endif // ifndef __OPENFLOW_OPEN_FLOW_MESSAGE_M_H

